---
- name: MariaDB Installation
  hosts: mariadb
  become: yes
  become_method: sudo
  ignore_unreachable: yes
  roles:
    - roles-mariadb

- name: Apache Installation
  hosts: apache
  become: yes
  become_method: sudo
  ignore_unreachable: yes
  roles:
    - roles-apache
...
